version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: basedeAlunos
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: